version: '3.8'

services:
# --- Database Service ---
  db:
    image: ankane/pgvector:latest
    container_name: attendance_db
    restart: always
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      # persistance keeps data on the lab coputer's desk
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d attendance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  app:
    build: .
    container_name: attendance_app
    # NETWORK: Allows the app to see the IP camera and DB on the same network
    network_mode: "host"
    privileged: true
    # devices:
    #   - "/dev/video0:/dev/video2"  # Adjust according to your camera device
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # External ACCESS: Maps your local directories into the container for logs, unknown faces, and face images
      - ./Face_images:/app/Face_images
      - ./unknown_faces:/app/unknown_faces
      - ./config:/app/config
      - ./templates:/app/templates
      - ./logs:/app/logs
      - ./recognized_faces:/app/recognized_faces
    environment:
      - PYTHONUNBUFFERED=1
